spring.application.name=service-auth
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_guide?currentSchema=tourist,admin,public
spring.datasource.username=guide
spring.datasource.password=guide123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

jwt.tourist-secret=TouristSecretKeyForAI-Digital-Guide-2026
jwt.admin-secret=AdminSecretKeyForAI-Digital-Guide-2026!!
jwt.tourist-expiration=604800000
jwt.admin-expiration=86400000

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
