spring.application.name=service-ai-proxy
server.port=8084

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_guide?currentSchema=admin,public
spring.datasource.username=guide
spring.datasource.password=guide123

deepseek.api-key=${DEEPSEEK_API_KEY:your-key}
qweather.api-key=${QWEATHER_API_KEY:your-key}
